const PlaidDataFormula = [
  {
    id: 13000000,
    place: "Food and Drink",
    hierarchy: "",
    category: "diet",
    co2PerMods: 274,
  },
  {
    id: 13001000,
    place: "Food and Drink, Bar",
    hierarchy: "",
    category: "",
    co2PerMods: 80,
  },
  {
    id: 13001001,
    place: "Food and Drink, Bar, Wine Bar",
    hierarchy: "",
    category: "",
    co2PerMods: 85,
  },
  {
    id: 13001002,
    place: "Food and Drink, Bar, Sports Bar",
    hierarchy: "",
    category: "",
    co2PerMods: 53,
  },
  {
    id: 13001003,
    place: "Food and Drink, Bar, Hotel Lounge",
    hierarchy: "",
    category: "",
    co2PerMods: 57,
  },
  {
    id: 13002000,
    place: "Food and Drink, Breweries",
    hierarchy: "",
    category: "",
    co2PerMods: 56,
  },
  {
    id: 13003000,
    place: "Food and Drink, Internet Cafes",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13004000,
    place: "Food and Drink, Nightlife",
    hierarchy: "",
    category: "",
    co2PerMods: 50,
  },
  {
    id: 13004001,
    place: "Food and Drink, Nightlife, Strip Club",
    hierarchy: "",
    category: "",
    co2PerMods: 50,
  },
  {
    id: 13004002,
    place: "Food and Drink, Nightlife, Night Clubs",
    hierarchy: "",
    category: "",
    co2PerMods: 50,
  },
  {
    id: 13004003,
    place: "Food and Drink, Nightlife, Karaoke",
    hierarchy: "",
    category: "",
    co2PerMods: 50,
  },
  {
    id: 13004004,
    place: "Food and Drink, Nightlife, Jazz and Blues Cafe",
    hierarchy: "",
    category: "",
    co2PerMods: 50,
  },
  {
    id: 13004005,
    place: "Food and Drink, Nightlife, Hookah Lounges",
    hierarchy: "",
    category: "",
    co2PerMods: 57,
  },
  {
    id: 13004006,
    place: "Food and Drink, Nightlife, Adult Entertainment",
    hierarchy: "",
    category: "",
    co2PerMods: 50,
  },
  {
    id: 13005000,
    place: "Food and Drink, Restaurants",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005001,
    place: "Food and Drink, Restaurants, Winery",
    hierarchy: "",
    category: "",
    co2PerMods: 90,
  },
  {
    id: 13005002,
    place: "Food and Drink, Restaurants, Vegan and Vegetarian",
    hierarchy: "",
    category: "",
    co2PerMods: 152,
  },
  {
    id: 13005003,
    place: "Food and Drink, Restaurants, Turkish",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005004,
    place: "Food and Drink, Restaurants, Thai",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005005,
    place: "Food and Drink, Restaurants, Swiss",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005006,
    place: "Food and Drink, Restaurants, Sushi",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005007,
    place: "Food and Drink, Restaurants, Steakhouses",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005008,
    place: "Food and Drink, Restaurants, Spanish",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005009,
    place: "Food and Drink, Restaurants, Seafood",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005010,
    place: "Food and Drink, Restaurants, Scandinavian",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005011,
    place: "Food and Drink, Restaurants, Portuguese",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005012,
    place: "Food and Drink, Restaurants, Pizza",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005013,
    place: "Food and Drink, Restaurants, Moroccan",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005014,
    place: "Food and Drink, Restaurants, Middle Eastern",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005015,
    place: "Food and Drink, Restaurants, Mexican",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005016,
    place: "Food and Drink, Restaurants, Mediterranean",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005017,
    place: "Food and Drink, Restaurants, Latin American",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005018,
    place: "Food and Drink, Restaurants, Korean",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005019,
    place: "Food and Drink, Restaurants, Juice Bar",
    hierarchy: "",
    category: "reusable",
    co2PerMods: 79,
  },
  {
    id: 13005020,
    place: "Food and Drink, Restaurants, Japanese",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005021,
    place: "Food and Drink, Restaurants, Italian",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005022,
    place: "Food and Drink, Restaurants, Indonesian",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005023,
    place: "Food and Drink, Restaurants, Indian",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005024,
    place: "Food and Drink, Restaurants, Ice Cream",
    hierarchy: "",
    category: "",
    co2PerMods: 165,
  },
  {
    id: 13005025,
    place: "Food and Drink, Restaurants, Greek",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005026,
    place: "Food and Drink, Restaurants, German",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005027,
    place: "Food and Drink, Restaurants, Gastropub",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005028,
    place: "Food and Drink, Restaurants, French",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005029,
    place: "Food and Drink, Restaurants, Food Truck",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005030,
    place: "Food and Drink, Restaurants, Fish and Chips",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005031,
    place: "Food and Drink, Restaurants, Filipino",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005032,
    place: "Food and Drink, Restaurants, Fast Food",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005033,
    place: "Food and Drink, Restaurants, Falafel",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005034,
    place: "Food and Drink, Restaurants, Ethiopian",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005035,
    place: "Food and Drink, Restaurants, Eastern European",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005036,
    place: "Food and Drink, Restaurants, Donuts",
    hierarchy: "",
    category: "",
    co2PerMods: 152,
  },
  {
    id: 13005037,
    place: "Food and Drink, Restaurants, Distillery",
    hierarchy: "",
    category: "",
    co2PerMods: 26,
  },
  {
    id: 13005038,
    place: "Food and Drink, Restaurants, Diners",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005039,
    place: "Food and Drink, Restaurants, Dessert",
    hierarchy: "",
    category: "",
    co2PerMods: 152,
  },
  {
    id: 13005040,
    place: "Food and Drink, Restaurants, Delis",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005041,
    place: "Food and Drink, Restaurants, Cupcake Shop",
    hierarchy: "",
    category: "diet",
    co2PerMods: 152,
  },
  {
    id: 13005042,
    place: "Food and Drink, Restaurants, Cuban",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005043,
    place: "Food and Drink, Restaurants, Coffee Shop",
    hierarchy: "",
    category: "reusable",
    co2PerMods: 67,
  },
  {
    id: 13005044,
    place: "Food and Drink, Restaurants, Chinese",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005045,
    place: "Food and Drink, Restaurants, Caribbean",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005046,
    place: "Food and Drink, Restaurants, Cajun",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005047,
    place: "Food and Drink, Restaurants, Cafe",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005048,
    place: "Food and Drink, Restaurants, Burrito",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005049,
    place: "Food and Drink, Restaurants, Burgers",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005050,
    place: "Food and Drink, Restaurants, Breakfast Spot",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005051,
    place: "Food and Drink, Restaurants, Brazilian",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005052,
    place: "Food and Drink, Restaurants, Barbecue",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005053,
    place: "Food and Drink, Restaurants, Bakery",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005054,
    place: "Food and Drink, Restaurants, Bagel Shop",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005055,
    place: "Food and Drink, Restaurants, Australian",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005056,
    place: "Food and Drink, Restaurants, Asian",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005057,
    place: "Food and Drink, Restaurants, American",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005058,
    place: "Food and Drink, Restaurants, African",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 13005059,
    place: "Food and Drink, Restaurants, Afghan",
    hierarchy: "",
    category: "diet",
    co2PerMods: 351,
  },
  {
    id: 18006000,
    place: "Service, Automotive",
    hierarchy: "",
    category: "",
    co2PerMods: 146,
  },
  {
    id: 18006001,
    place: "Service, Automotive, Towing",
    hierarchy: "",
    category: "",
    co2PerMods: 93,
  },
  {
    id: 18006002,
    place: "Service, Automotive, Motorcycle, Moped and Scooter Repair",
    hierarchy: "",
    category: "",
    co2PerMods: 264,
  },
  {
    id: 18006003,
    place: "Service, Automotive, Maintenance and Repair",
    hierarchy: "",
    category: "",
    co2PerMods: 264,
  },
  {
    id: 18006004,
    place: "Service, Automotive, Car Wash and Detail",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18006005,
    place: "Service, Automotive, Car Appraisers",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18006006,
    place: "Service, Automotive, Auto Transmission",
    hierarchy: "",
    category: "",
    co2PerMods: 354,
  },
  {
    id: 18006007,
    place: "Service, Automotive, Auto Tires",
    hierarchy: "",
    category: "",
    co2PerMods: 57,
  },
  {
    id: 18006008,
    place: "Service, Automotive, Auto Smog Check",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18006009,
    place: "Service, Automotive, Auto Oil and Lube",
    hierarchy: "",
    category: "",
    co2PerMods: 283,
  },
  {
    id: 18007000,
    place: "Service, Business and Strategy Consulting",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18008000,
    place: "Service, Business Services",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18008001,
    place: "Service, Business Services, Printing and Publishing",
    hierarchy: "",
    category: "",
    co2PerMods: 8,
  },
  {
    id: 18009000,
    place: "Service, Cable",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18010000,
    place: "Service, Chemicals and Gasses",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18011000,
    place: "Service, Cleaning",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18012000,
    place: "Service, Computers",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18012001,
    place: "Service, Computers, Maintenance and Repair",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18012002,
    place: "Service, Computers, Software Development",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18013000,
    place: "Service, Construction",
    hierarchy: "",
    category: "",
    co2PerMods: 356,
  },
  {
    id: 18013001,
    place: "Service, Construction, Specialty",
    hierarchy: "",
    category: "",
    co2PerMods: 356,
  },
  {
    id: 18013002,
    place: "Service, Construction, Roofers",
    hierarchy: "",
    category: "",
    co2PerMods: 38,
  },
  {
    id: 18013003,
    place: "Service, Construction, Painting",
    hierarchy: "",
    category: "",
    co2PerMods: 330,
  },
  {
    id: 18013004,
    place: "Service, Construction, Masonry",
    hierarchy: "",
    category: "",
    co2PerMods: 317,
  },
  {
    id: 18013005,
    place: "Service, Construction, Infrastructure",
    hierarchy: "",
    category: "",
    co2PerMods: 1761,
  },
  {
    id: 18013006,
    place: "Service, Construction, Heating, Ventilating and Air Conditioning",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18013007,
    place: "Service, Construction, Electricians",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18013008,
    place: "Service, Construction, Contractors",
    hierarchy: "",
    category: "",
    co2PerMods: 356,
  },
  {
    id: 18013009,
    place: "Service, Construction, Carpet and Flooring",
    hierarchy: "",
    category: "",
    co2PerMods: 396,
  },
  {
    id: 18013010,
    place: "Service, Construction, Carpenters",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18021000,
    place: "Service, Food and Beverage",
    hierarchy: "",
    category: "",
    co2PerMods: 246,
  },
  {
    id: 18021001,
    place: "Service, Food and Beverage, Distribution",
    hierarchy: "",
    category: "",
    co2PerMods: 217,
  },
  {
    id: 18021002,
    place: "Service, Food and Beverage, Catering",
    hierarchy: "",
    category: "",
    co2PerMods: 274,
  },
  {
    id: 18022000,
    place: "Service, Funeral Services",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18023000,
    place: "Service, Geological",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18024000,
    place: "Service, Home Improvement",
    hierarchy: "",
    category: "",
    co2PerMods: 152,
  },
  {
    id: 18024001,
    place: "Service, Home Improvement, Upholstery",
    hierarchy: "",
    category: "",
    co2PerMods: 180,
  },
  {
    id: 18024002,
    place: "Service, Home Improvement, Tree Service",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18024003,
    place: "Service, Home Improvement, Swimming Pool Maintenance and Services",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18024004,
    place: "Service, Home Improvement, Storage",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18024005,
    place: "Service, Home Improvement, Roofers",
    hierarchy: "",
    category: "",
    co2PerMods: 38,
  },
  {
    id: 18024006,
    place: "Service, Home Improvement, Pools and Spas",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18024007,
    place: "Service, Home Improvement, Plumbing",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18024008,
    place: "Service, Home Improvement, Pest Control",
    hierarchy: "",
    category: "",
    co2PerMods: 470,
  },
  {
    id: 18024009,
    place: "Service, Home Improvement, Painting",
    hierarchy: "",
    category: "",
    co2PerMods: 330,
  },
  {
    id: 18024010,
    place: "Service, Home Improvement, Movers",
    hierarchy: "",
    category: "",
    co2PerMods: 497,
  },
  {
    id: 18024011,
    place: "Service, Home Improvement, Mobile Homes",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18024012,
    place: "Service, Home Improvement, Lighting Fixtures",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18024013,
    place: "Service, Home Improvement, Landscaping and Gardeners",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18024014,
    place: "Service, Home Improvement, Kitchens",
    hierarchy: "",
    category: "",
    co2PerMods: 356,
  },
  {
    id: 18024015,
    place: "Service, Home Improvement, Interior Design",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18024016,
    place: "Service, Home Improvement, Housewares",
    hierarchy: "",
    category: "",
    co2PerMods: 180,
  },
  {
    id: 18024017,
    place: "Service, Home Improvement, Home Inspection Services",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18024018,
    place: "Service, Home Improvement, Home Appliances",
    hierarchy: "",
    category: "",
    co2PerMods: 700,
  },
  {
    id: 18024019,
    place:
      "Service, Home Improvement, Heating, Ventilation and Air Conditioning",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18024020,
    place: "Service, Home Improvement, Hardware and Services",
    hierarchy: "",
    category: "",
    co2PerMods: 268,
  },
  {
    id: 18024021,
    place: "Service, Home Improvement, Fences, Fireplaces and Garage Doors",
    hierarchy: "",
    category: "",
    co2PerMods: 268,
  },
  {
    id: 18024022,
    place: "Service, Home Improvement, Electricians",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18024023,
    place: "Service, Home Improvement, Doors and Windows",
    hierarchy: "",
    category: "",
    co2PerMods: 268,
  },
  {
    id: 18024024,
    place: "Service, Home Improvement, Contractors",
    hierarchy: "",
    category: "",
    co2PerMods: 152,
  },
  {
    id: 18024025,
    place: "Service, Home Improvement, Carpet and Flooring",
    hierarchy: "",
    category: "",
    co2PerMods: 396,
  },
  {
    id: 18024026,
    place: "Service, Home Improvement, Carpenters",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18024027,
    place: "Service, Home Improvement, Architects",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18032000,
    place: "Service, Leather",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18033000,
    place: "Service, Legal",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18034000,
    place: "Service, Logging and Sawmills",
    hierarchy: "",
    category: "",
    co2PerMods: 42,
  },
  {
    id: 18035000,
    place: "Service, Machine Shops",
    hierarchy: "",
    category: "",
    co2PerMods: 42,
  },
  {
    id: 18036000,
    place: "Service, Management",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18037000,
    place: "Service, Manufacturing",
    hierarchy: "",
    category: "",
    co2PerMods: 669,
  },
  {
    id: 18037001,
    place: "Service, Manufacturing, Apparel and Fabric Products",
    hierarchy: "",
    category: "",
    co2PerMods: 414,
  },
  {
    id: 18037002,
    place: "Service, Manufacturing, Chemicals and Gasses",
    hierarchy: "",
    category: "",
    co2PerMods: 777,
  },
  {
    id: 18037003,
    place: "Service, Manufacturing, Computers and Office Machines",
    hierarchy: "",
    category: "",
    co2PerMods: 110,
  },
  {
    id: 18037004,
    place: "Service, Manufacturing, Electrical Equipment and Components",
    hierarchy: "",
    category: "",
    co2PerMods: 110,
  },
  {
    id: 18037005,
    place: "Service, Manufacturing, Food and Beverage",
    hierarchy: "",
    category: "",
    co2PerMods: 434,
  },
  {
    id: 18037006,
    place: "Service, Manufacturing, Furniture and Fixtures",
    hierarchy: "",
    category: "",
    co2PerMods: 180,
  },
  {
    id: 18037007,
    place: "Service, Manufacturing, Glass Products",
    hierarchy: "",
    category: "",
    co2PerMods: 839,
  },
  {
    id: 18037008,
    place: "Service, Manufacturing, Industrial Machinery and Equipment",
    hierarchy: "",
    category: "",
    co2PerMods: 173,
  },
  {
    id: 18037009,
    place: "Service, Manufacturing, Leather Goods",
    hierarchy: "",
    category: "",
    co2PerMods: 414,
  },
  {
    id: 18037010,
    place: "Service, Manufacturing, Metal Products",
    hierarchy: "",
    category: "",
    co2PerMods: 408,
  },
  {
    id: 18037011,
    place: "Service, Manufacturing, Nonmetallic Mineral Products",
    hierarchy: "",
    category: "",
    co2PerMods: 3900,
  },
  {
    id: 18037012,
    place: "Service, Manufacturing, Paper Products",
    hierarchy: "",
    category: "",
    co2PerMods: 581,
  },
  {
    id: 18037013,
    place: "Service, Manufacturing, Petroleum",
    hierarchy: "",
    category: "",
    co2PerMods: 2022,
  },
  {
    id: 18037014,
    place: "Service, Manufacturing, Plastic Products",
    hierarchy: "",
    category: "",
    co2PerMods: 531,
  },
  {
    id: 18037015,
    place: "Service, Manufacturing, Rubber Products",
    hierarchy: "",
    category: "",
    co2PerMods: 531,
  },
  {
    id: 18037016,
    place: "Service, Manufacturing, Service Instruments",
    hierarchy: "",
    category: "",
    co2PerMods: 173,
  },
  {
    id: 18037017,
    place: "Service, Manufacturing, Textiles",
    hierarchy: "",
    category: "",
    co2PerMods: 414,
  },
  {
    id: 18037018,
    place: "Service, Manufacturing, Tobacco",
    hierarchy: "",
    category: "",
    co2PerMods: 434,
  },
  {
    id: 18037019,
    place: "Service, Manufacturing, Transportation Equipment",
    hierarchy: "",
    category: "",
    co2PerMods: 358,
  },
  {
    id: 18037020,
    place: "Service, Manufacturing, Wood Products",
    hierarchy: "",
    category: "",
    co2PerMods: 581,
  },
  {
    id: 18038000,
    place: "Service, Media Production",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18039000,
    place: "Service, Metals",
    hierarchy: "",
    category: "",
    co2PerMods: 408,
  },
  {
    id: 18040000,
    place: "Service, Mining",
    hierarchy: "",
    category: "",
    co2PerMods: 2646,
  },
  {
    id: 18040001,
    place: "Service, Mining, Coal",
    hierarchy: "",
    category: "",
    co2PerMods: 7380,
  },
  {
    id: 18040002,
    place: "Service, Mining, Metal",
    hierarchy: "",
    category: "",
    co2PerMods: 279,
  },
  {
    id: 18040003,
    place: "Service, Mining, Non-Metallic Minerals",
    hierarchy: "",
    category: "",
    co2PerMods: 279,
  },
  {
    id: 18041000,
    place: "Service, News Reporting",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18042000,
    place: "Service, Oil and Gas",
    hierarchy: "",
    category: "",
    co2PerMods: 2022,
  },
  {
    id: 18043000,
    place: "Service, Packaging",
    hierarchy: "",
    category: "",
    co2PerMods: 186,
  },
  {
    id: 18044000,
    place: "Service, Paper",
    hierarchy: "",
    category: "",
    co2PerMods: 8,
  },
  {
    id: 18029000,
    place: "Service, Industrial Machinery and Vehicles",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18045008,
    place: "Service, Personal Care, Laundry and Garment Services",
    hierarchy: "",
    category: "",
    co2PerMods: 1100,
  },
  {
    id: 18045009,
    place: "Service, Personal Care, Hair Salons and Barbers",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18045010,
    place: "Service, Personal Care, Hair Removal",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18046000,
    place: "Service, Petroleum",
    hierarchy: "",
    category: "",
    co2PerMods: 2022,
  },
  {
    id: 18047000,
    place: "Service, Photography",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18048000,
    place: "Service, Plastics",
    hierarchy: "",
    category: "",
    co2PerMods: 531,
  },
  {
    id: 18049000,
    place: "Service, Rail",
    hierarchy: "",
    category: "",
    co2PerMods: 302,
  },
  {
    id: 18055000,
    place: "Service, Rubber",
    hierarchy: "",
    category: "",
    co2PerMods: 531,
  },
  {
    id: 18056000,
    place: "Service, Scientific",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18057000,
    place: "Service, Security and Safety",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18058000,
    place: "Service, Shipping and Freight",
    hierarchy: "",
    category: "",
    co2PerMods: 221,
  },
  {
    id: 18059000,
    place: "Service, Software Development",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18060000,
    place: "Service, Storage",
    hierarchy: "",
    category: "",
    co2PerMods: 93,
  },
  {
    id: 18061000,
    place: "Service, Subscription",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18062000,
    place: "Service, Tailors",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18063000,
    place: "Service, Telecommunication Services",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18064000,
    place: "Service, Textiles",
    hierarchy: "",
    category: "",
    co2PerMods: 414,
  },
  {
    id: 18065000,
    place: "Service, Tourist Information and Services",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18066000,
    place: "Service, Transportation",
    hierarchy: "",
    category: "",
    co2PerMods: 358,
  },
  {
    id: 18067000,
    place: "Service, Travel Agents and Tour Operators",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18068000,
    special: "Service, Utilities",
    hierarchy: "",
    category: "",
    co2PerMods: 1423,
  },
  {
    id: 18068001,
    special: "Service, Utilities, Water",
    hierarchy: "",
    category: "",
    co2PerMods: 142,
  },
  {
    id: 18068002,
    special: "Service, Utilities, Sanitary and Waste Management",
    hierarchy: "",
    category: "",
    co2PerMods: 973,
  },
  {
    id: 18068003,
    place: "Service, Utilities, Heating, Ventilating, and Air Conditioning",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18068004,
    special: "Service, Utilities, Gas",
    hierarchy: "",
    category: "",
    co2PerMods: 5079,
  },
  {
    id: 18068005,
    special: "Service, Utilities, Electric",
    hierarchy: "",
    category: "",
    co2PerMods: 2342,
  },
  {
    id: 18069000,
    place: "Service, Veterinarians",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18070000,
    place: "Service, Water and Waste Management",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18071000,
    place: "Service, Web Design and Development",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 18072000,
    place: "Service, Welding",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 18073000,
    place: "Service, Agriculture and Forestry",
    hierarchy: "",
    category: "",
    co2PerMods: 4091,
  },
  {
    id: 18073001,
    place: "Service, Agriculture and Forestry, Crop Production",
    hierarchy: "",
    category: "",
    co2PerMods: 5323,
  },
  {
    id: 18073002,
    place: "Service, Agriculture and Forestry, Forestry",
    hierarchy: "",
    category: "",
    co2PerMods: 140,
  },
  {
    id: 18073003,
    place: "Service, Agriculture and Forestry, Livestock and Animals",
    hierarchy: "",
    category: "",
    co2PerMods: 6810,
  },
  {
    id: 18073004,
    place: "Service, Agriculture and Forestry, Services",
    hierarchy: "",
    category: "",
    co2PerMods: 4091,
  },
  {
    id: 18074000,
    place: "Service, Art and Graphic Design",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 19000000,
    place: "Shops",
    hierarchy: "",
    category: "",
    co2PerMods: 518,
  },
  {
    id: 19001000,
    place: "Shops, Adult",
    hierarchy: "",
    category: "",
    co2PerMods: 190,
  },
  {
    id: 19002000,
    place: "Shops, Antiques",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 19003000,
    place: "Shops, Arts and Crafts",
    hierarchy: "",
    category: "",
    co2PerMods: 181,
  },
  {
    id: 19004000,
    place: "Shops, Auctions",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 19005000,
    place: "Shops, Automotive",
    hierarchy: "",
    category: "",
    co2PerMods: 396,
  },
  {
    id: 19005001,
    place: "Shops, Automotive, Used Car Dealers",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 19005002,
    place: "Shops, Automotive, Salvage Yards",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 19005003,
    place: "Shops, Automotive, RVs and Motor Homes",
    hierarchy: "",
    category: "",
    co2PerMods: 913,
  },
  {
    id: 19005004,
    place: "Shops, Automotive, Motorcycles, Mopeds and Scooters",
    hierarchy: "",
    category: "",
    co2PerMods: 913,
  },
  {
    id: 19005005,
    place: "Shops, Automotive, Classic and Antique Car",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 19005006,
    place: "Shops, Automotive, Car Parts and Accessories",
    hierarchy: "",
    category: "",
    co2PerMods: 264,
  },
  {
    id: 19005007,
    place: "Shops, Automotive, Car Dealers and Leasing",
    hierarchy: "",
    category: "",
    co2PerMods: 680,
  },
  {
    id: 19006000,
    place: "Shops, Beauty Products",
    hierarchy: "",
    category: "",
    co2PerMods: 40,
  },
  {
    id: 19007000,
    place: "Shops, Bicycles",
    hierarchy: "",
    category: "",
    co2PerMods: 481,
  },
  {
    id: 19008000,
    place: "Shops, Boat Dealers",
    hierarchy: "",
    category: "",
    co2PerMods: 913,
  },
  {
    id: 19009000,
    place: "Shops, Bookstores",
    hierarchy: "",
    category: "",
    co2PerMods: 181,
  },
  {
    id: 19010000,
    place: "Shops, Cards and Stationery",
    hierarchy: "",
    category: "",
    co2PerMods: 181,
  },
  {
    id: 19011000,
    place: "Shops, Children",
    hierarchy: "",
    category: "",
    co2PerMods: 668,
  },
  {
    id: 19012000,
    place: "Shops, Clothing and Accessories",
    hierarchy: "",
    category: "",
    co2PerMods: 668,
  },
  {
    id: 19012001,
    place: "Shops, Clothing and Accessories, Women's Store",
    hierarchy: "",
    category: "",
    co2PerMods: 668,
  },
  {
    id: 19012002,
    place: "Shops, Clothing and Accessories, Swimwear",
    hierarchy: "",
    category: "",
    co2PerMods: 668,
  },
  {
    id: 19012003,
    place: "Shops, Clothing and Accessories, Shoe Store",
    hierarchy: "",
    category: "",
    co2PerMods: 668,
  },
  {
    id: 19012004,
    place: "Shops, Clothing and Accessories, Men's Store",
    hierarchy: "",
    category: "",
    co2PerMods: 668,
  },
  {
    id: 19012005,
    place: "Shops, Clothing and Accessories, Lingerie Store",
    hierarchy: "",
    category: "",
    co2PerMods: 190,
  },
  {
    id: 19012006,
    place: "Shops, Clothing and Accessories, Kids' Store",
    hierarchy: "",
    category: "",
    co2PerMods: 668,
  },
  {
    id: 19012007,
    place: "Shops, Clothing and Accessories, Boutique",
    hierarchy: "",
    category: "",
    co2PerMods: 668,
  },
  {
    id: 19012008,
    place: "Shops, Clothing and Accessories, Accessories Store",
    hierarchy: "",
    category: "",
    co2PerMods: 668,
  },
  {
    id: 19013000,
    place: "Shops, Computers and Electronics",
    hierarchy: "",
    category: "",
    co2PerMods: 386,
  },
  {
    id: 19013001,
    place: "Shops, Computers and Electronics, Video Games",
    hierarchy: "",
    category: "",
    co2PerMods: 386,
  },
  {
    id: 19013002,
    place: "Shops, Computers and Electronics, Mobile Phones",
    hierarchy: "",
    category: "",
    co2PerMods: 386,
  },
  {
    id: 19013003,
    place: "Shops, Computers and Electronics, Cameras",
    hierarchy: "",
    category: "",
    co2PerMods: 386,
  },
  {
    id: 19014000,
    place: "Shops, Construction Supplies",
    hierarchy: "",
    category: "",
    co2PerMods: 356,
  },
  {
    id: 19015000,
    place: "Shops, Convenience Stores",
    hierarchy: "",
    category: "",
    co2PerMods: 884,
  },
  {
    id: 19016000,
    place: "Shops, Costumes",
    hierarchy: "",
    category: "",
    co2PerMods: 668,
  },
  {
    id: 19017000,
    place: "Shops, Dance and Music",
    hierarchy: "",
    category: "",
    co2PerMods: 668,
  },
  {
    id: 19018000,
    place: "Shops, Department Stores",
    hierarchy: "",
    category: "",
    co2PerMods: 668,
  },
  {
    id: 19019000,
    digital: "Shops, Digital Purchase",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 19020000,
    place: "Shops, Discount Stores",
    hierarchy: "",
    category: "",
    co2PerMods: 884,
  },
  {
    id: 19021000,
    place: "Shops, Electrical Equipment",
    hierarchy: "",
    category: "",
    co2PerMods: 386,
  },
  {
    id: 19022000,
    place: "Shops, Equipment Rental",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 19023000,
    place: "Shops, Flea Markets",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 19024000,
    place: "Shops, Florists",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 19025000,
    place: "Shops, Food and Beverage Store",
    hierarchy: "",
    category: "",
    co2PerMods: 884,
  },
  {
    id: 19025001,
    place: "Shops, Food and Beverage Store, Specialty",
    hierarchy: "",
    category: "",
    co2PerMods: 884,
  },
  {
    id: 19025002,
    place: "Shops, Food and Beverage Store, Health Food",
    hierarchy: "",
    category: "",
    co2PerMods: 884,
  },
  {
    id: 19025003,
    place: "Shops, Food and Beverage Store, Farmers Markets",
    hierarchy: "",
    category: "",
    co2PerMods: 884,
  },
  {
    id: 19025004,
    place: "Shops, Food and Beverage Store, Beer, Wine and Spirits",
    hierarchy: "",
    category: "",
    co2PerMods: 360,
  },
  {
    id: 19026000,
    place: "Shops, Fuel Dealer",
    hierarchy: "",
    category: "",
    co2PerMods: 4080,
  },
  {
    id: 19027000,
    place: "Shops, Furniture and Home Decor",
    hierarchy: "",
    category: "",
    co2PerMods: 180,
  },
  {
    id: 19028000,
    place: "Shops, Gift and Novelty",
    hierarchy: "",
    category: "",
    co2PerMods: 181,
  },
  {
    id: 19029000,
    place: "Shops, Glasses and Optometrist",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 19030000,
    place: "Shops, Hardware Store",
    hierarchy: "",
    category: "",
    co2PerMods: 356,
  },
  {
    id: 19031000,
    place: "Shops, Hobby and Collectibles",
    hierarchy: "",
    category: "",
    co2PerMods: 181,
  },
  {
    id: 19032000,
    place: "Shops, Industrial Supplies",
    hierarchy: "",
    category: "",
    co2PerMods: 669,
  },
  {
    id: 19033000,
    place: "Shops, Jewelry and Watches",
    hierarchy: "",
    category: "",
    co2PerMods: 400,
  },
  {
    id: 19034000,
    place: "Shops, Luggage",
    hierarchy: "",
    category: "",
    co2PerMods: 465,
  },
  {
    id: 19035000,
    place: "Shops, Marine Supplies",
    hierarchy: "",
    category: "",
    co2PerMods: 669,
  },
  {
    id: 19036000,
    place: "Shops, Music, Video and DVD",
    hierarchy: "",
    category: "",
    co2PerMods: 157,
  },
  {
    id: 19037000,
    place: "Shops, Musical Instruments",
    hierarchy: "",
    category: "",
    co2PerMods: 292,
  },
  {
    id: 19038000,
    place: "Shops, Newsstands",
    hierarchy: "",
    category: "",
    co2PerMods: 105,
  },
  {
    id: 19039000,
    place: "Shops, Office Supplies",
    hierarchy: "",
    category: "",
    co2PerMods: 460,
  },
  {
    id: 19040000,
    place: "Shops, Outlet",
    hierarchy: "",
    category: "",
    co2PerMods: 668,
  },
  {
    id: 19040001,
    place: "Shops, Outlet, Women's Store",
    hierarchy: "",
    category: "",
    co2PerMods: 668,
  },
  {
    id: 19040002,
    place: "Shops, Outlet, Swimwear",
    hierarchy: "",
    category: "",
    co2PerMods: 668,
  },
  {
    id: 19040003,
    place: "Shops, Outlet, Shoe Store",
    hierarchy: "",
    category: "",
    co2PerMods: 668,
  },
  {
    id: 19040004,
    place: "Shops, Outlet, Men's Store",
    hierarchy: "",
    category: "",
    co2PerMods: 668,
  },
  {
    id: 19040005,
    place: "Shops, Outlet, Lingerie Store",
    hierarchy: "",
    category: "",
    co2PerMods: 190,
  },
  {
    id: 19040006,
    place: "Shops, Outlet, Kids' Store",
    hierarchy: "",
    category: "",
    co2PerMods: 668,
  },
  {
    id: 19040007,
    place: "Shops, Outlet, Boutique",
    hierarchy: "",
    category: "",
    co2PerMods: 668,
  },
  {
    id: 19040008,
    place: "Shops, Outlet, Accessories Store",
    hierarchy: "",
    category: "",
    co2PerMods: 668,
  },
  {
    id: 19041000,
    place: "Shops, Pawn Shops",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 19042000,
    place: "Shops, Pets",
    hierarchy: "",
    category: "",
    co2PerMods: 240,
  },
  {
    id: 19043000,
    place: "Shops, Pharmacies",
    hierarchy: "",
    category: "",
    co2PerMods: 240,
  },
  {
    id: 19044000,
    place: "Shops, Photos and Frames",
    hierarchy: "",
    category: "",
    co2PerMods: 195,
  },
  {
    id: 19045000,
    place: "Shops, Shopping Centers and Malls",
    hierarchy: "",
    category: "",
    co2PerMods: 668,
  },
  {
    id: 19046000,
    place: "Shops, Sporting Goods",
    hierarchy: "",
    category: "",
    co2PerMods: 500,
  },
  {
    id: 19047000,
    place: "Shops, Supermarkets and Groceries",
    hierarchy: "",
    category: "",
    co2PerMods: 884,
  },
  {
    id: 19048000,
    place: "Shops, Tobacco",
    hierarchy: "",
    category: "",
    co2PerMods: 286,
  },
  {
    id: 19049000,
    place: "Shops, Toys",
    hierarchy: "",
    category: "",
    co2PerMods: 412,
  },
  {
    id: 19050000,
    place: "Shops, Vintage and Thrift",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 19051000,
    place: "Shops, Warehouses and Wholesale Stores",
    hierarchy: "",
    category: "",
    co2PerMods: 884,
  },
  {
    id: 19052000,
    place: "Shops, Wedding and Bridal",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 19053000,
    place: "Shops, Wholesale",
    hierarchy: "",
    category: "",
    co2PerMods: 884,
  },
  {
    id: 19054000,
    place: "Shops, Lawn and Garden",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 22000000,
    place: "Travel",
    hierarchy: "",
    category: "",
    co2PerMods: 453,
  },
  {
    id: 22001000,
    place: "Travel, Airlines and Aviation Services",
    hierarchy: "",
    category: "",
    co2PerMods: 1283,
  },
  {
    id: 22002000,
    place: "Travel, Airports",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 22003000,
    place: "Travel, Boat",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 22004000,
    place: "Travel, Bus Stations",
    hierarchy: "",
    category: "",
    co2PerMods: 660,
  },
  {
    id: 22005000,
    place: "Travel, Car and Truck Rentals",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
  {
    id: 22006000,
    place: "Travel, Car Service",
    hierarchy: "",
    category: "",
    co2PerMods: 206,
  },
  {
    id: 22006001,
    place: "Travel, Car Service, Ride Share",
    hierarchy: "",
    category: "",
    co2PerMods: 206,
  },
  {
    id: 22007000,
    place: "Travel, Charter Buses",
    hierarchy: "",
    category: "",
    co2PerMods: 660,
  },
  {
    id: 22008000,
    place: "Travel, Cruises",
    hierarchy: "",
    category: "",
    co2PerMods: 553,
  },
  {
    id: 22009000,
    place: "Travel, Gas Stations",
    hierarchy: "",
    category: "",
    co2PerMods: 4080,
  },
  {
    id: 22010000,
    place: "Travel, Heliports",
    hierarchy: "",
    category: "",
    co2PerMods: 491,
  },
  {
    id: 22011000,
    place: "Travel, Limos and Chauffeurs",
    hierarchy: "",
    category: "",
    co2PerMods: 190,
  },
  {
    id: 22012000,
    place: "Travel, Lodging",
    hierarchy: "",
    category: "",
    co2PerMods: 173,
  },
  {
    id: 22012001,
    place: "Travel, Lodging, Resorts",
    hierarchy: "",
    category: "",
    co2PerMods: 173,
  },
  {
    id: 22012002,
    place: "Travel, Lodging, Lodges and Vacation Rentals",
    hierarchy: "",
    category: "",
    co2PerMods: 173,
  },
  {
    id: 22012003,
    place: "Travel, Lodging, Hotels and Motels",
    hierarchy: "",
    category: "",
    co2PerMods: 173,
  },
  {
    id: 22012004,
    place: "Travel, Lodging, Hostels",
    hierarchy: "",
    category: "",
    co2PerMods: 173,
  },
  {
    id: 22012005,
    place: "Travel, Lodging, Cottages and Cabins",
    hierarchy: "",
    category: "",
    co2PerMods: 173,
  },
  {
    id: 22012006,
    place: "Travel, Lodging, Bed and Breakfasts",
    hierarchy: "",
    category: "",
    co2PerMods: 173,
  },
  {
    id: 22013000,
    place: "Travel, Parking",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 22014000,
    place: "Travel, Public Transportation Services",
    hierarchy: "",
    category: "",
    co2PerMods: 529,
  },
  {
    id: 22015000,
    place: "Travel, Rail",
    hierarchy: "",
    category: "",
    co2PerMods: 193,
  },
  {
    id: 22016000,
    place: "Travel, Taxi",
    hierarchy: "",
    category: "",
    co2PerMods: 152,
  },
  {
    id: 22017000,
    place: "Travel, Tolls and Fees",
    hierarchy: "",
    category: "",
    co2PerMods: 0,
  },
  {
    id: 22018000,
    place: "Travel, Transportation Centers",
    hierarchy: "",
    category: "",
    co2PerMods: 1,
  },
];

export default PlaidDataFormula;
